# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joao/Desktop/4ºAno/IC/P/IC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joao/Desktop/4ºAno/IC/P/IC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joao/Desktop/4ºAno/IC/P/IC/CMakeFiles /home/joao/Desktop/4ºAno/IC/P/IC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joao/Desktop/4ºAno/IC/P/IC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imageBright

# Build rule for target.
imageBright: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imageBright
.PHONY : imageBright

# fast build rule for target.
imageBright/fast:
	$(MAKE) -f CMakeFiles/imageBright.dir/build.make CMakeFiles/imageBright.dir/build
.PHONY : imageBright/fast

#=============================================================================
# Target rules for targets named imageRotate

# Build rule for target.
imageRotate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imageRotate
.PHONY : imageRotate

# fast build rule for target.
imageRotate/fast:
	$(MAKE) -f CMakeFiles/imageRotate.dir/build.make CMakeFiles/imageRotate.dir/build
.PHONY : imageRotate/fast

#=============================================================================
# Target rules for targets named imageNeg

# Build rule for target.
imageNeg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imageNeg
.PHONY : imageNeg

# fast build rule for target.
imageNeg/fast:
	$(MAKE) -f CMakeFiles/imageNeg.dir/build.make CMakeFiles/imageNeg.dir/build
.PHONY : imageNeg/fast

#=============================================================================
# Target rules for targets named imageCopy

# Build rule for target.
imageCopy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imageCopy
.PHONY : imageCopy

# fast build rule for target.
imageCopy/fast:
	$(MAKE) -f CMakeFiles/imageCopy.dir/build.make CMakeFiles/imageCopy.dir/build
.PHONY : imageCopy/fast

imageBright.o: imageBright.cpp.o

.PHONY : imageBright.o

# target to build an object file
imageBright.cpp.o:
	$(MAKE) -f CMakeFiles/imageBright.dir/build.make CMakeFiles/imageBright.dir/imageBright.cpp.o
.PHONY : imageBright.cpp.o

imageBright.i: imageBright.cpp.i

.PHONY : imageBright.i

# target to preprocess a source file
imageBright.cpp.i:
	$(MAKE) -f CMakeFiles/imageBright.dir/build.make CMakeFiles/imageBright.dir/imageBright.cpp.i
.PHONY : imageBright.cpp.i

imageBright.s: imageBright.cpp.s

.PHONY : imageBright.s

# target to generate assembly for a file
imageBright.cpp.s:
	$(MAKE) -f CMakeFiles/imageBright.dir/build.make CMakeFiles/imageBright.dir/imageBright.cpp.s
.PHONY : imageBright.cpp.s

imageCopy.o: imageCopy.cpp.o

.PHONY : imageCopy.o

# target to build an object file
imageCopy.cpp.o:
	$(MAKE) -f CMakeFiles/imageCopy.dir/build.make CMakeFiles/imageCopy.dir/imageCopy.cpp.o
.PHONY : imageCopy.cpp.o

imageCopy.i: imageCopy.cpp.i

.PHONY : imageCopy.i

# target to preprocess a source file
imageCopy.cpp.i:
	$(MAKE) -f CMakeFiles/imageCopy.dir/build.make CMakeFiles/imageCopy.dir/imageCopy.cpp.i
.PHONY : imageCopy.cpp.i

imageCopy.s: imageCopy.cpp.s

.PHONY : imageCopy.s

# target to generate assembly for a file
imageCopy.cpp.s:
	$(MAKE) -f CMakeFiles/imageCopy.dir/build.make CMakeFiles/imageCopy.dir/imageCopy.cpp.s
.PHONY : imageCopy.cpp.s

imageNeg.o: imageNeg.cpp.o

.PHONY : imageNeg.o

# target to build an object file
imageNeg.cpp.o:
	$(MAKE) -f CMakeFiles/imageNeg.dir/build.make CMakeFiles/imageNeg.dir/imageNeg.cpp.o
.PHONY : imageNeg.cpp.o

imageNeg.i: imageNeg.cpp.i

.PHONY : imageNeg.i

# target to preprocess a source file
imageNeg.cpp.i:
	$(MAKE) -f CMakeFiles/imageNeg.dir/build.make CMakeFiles/imageNeg.dir/imageNeg.cpp.i
.PHONY : imageNeg.cpp.i

imageNeg.s: imageNeg.cpp.s

.PHONY : imageNeg.s

# target to generate assembly for a file
imageNeg.cpp.s:
	$(MAKE) -f CMakeFiles/imageNeg.dir/build.make CMakeFiles/imageNeg.dir/imageNeg.cpp.s
.PHONY : imageNeg.cpp.s

imageRotate.o: imageRotate.cpp.o

.PHONY : imageRotate.o

# target to build an object file
imageRotate.cpp.o:
	$(MAKE) -f CMakeFiles/imageRotate.dir/build.make CMakeFiles/imageRotate.dir/imageRotate.cpp.o
.PHONY : imageRotate.cpp.o

imageRotate.i: imageRotate.cpp.i

.PHONY : imageRotate.i

# target to preprocess a source file
imageRotate.cpp.i:
	$(MAKE) -f CMakeFiles/imageRotate.dir/build.make CMakeFiles/imageRotate.dir/imageRotate.cpp.i
.PHONY : imageRotate.cpp.i

imageRotate.s: imageRotate.cpp.s

.PHONY : imageRotate.s

# target to generate assembly for a file
imageRotate.cpp.s:
	$(MAKE) -f CMakeFiles/imageRotate.dir/build.make CMakeFiles/imageRotate.dir/imageRotate.cpp.s
.PHONY : imageRotate.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... imageBright"
	@echo "... imageRotate"
	@echo "... imageNeg"
	@echo "... edit_cache"
	@echo "... imageCopy"
	@echo "... imageBright.o"
	@echo "... imageBright.i"
	@echo "... imageBright.s"
	@echo "... imageCopy.o"
	@echo "... imageCopy.i"
	@echo "... imageCopy.s"
	@echo "... imageNeg.o"
	@echo "... imageNeg.i"
	@echo "... imageNeg.s"
	@echo "... imageRotate.o"
	@echo "... imageRotate.i"
	@echo "... imageRotate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

